### ISSUE TITLE
RF Charging breaks questing

### ISSUE THREAD

**Issue by CaiganMythFang** [Funwayguy/RFExpansion#2]
**Current Quest Database** : https://drive.google.com/open?id=0B7jvvxp1wXVVUEI5NTNiZUdkcTQ
**Download for the entire modpack (currently in a Beta phase)** : https://forum.feed-the-beast.com/threads/1-7-10-the-ferret-business-wip-hqm-350-quests-v-0-1-4.64930/page-222#post-1714281
**Minecraft Version** : 1.7.10
**Forge Version** : 1614
**Better Questing version** : 1.0.141
**RF Expansion Version** : 1.0.13
**Other BQ Extensions** : Questbook, Standard

When using the RF Submission Station to fill an RF Charge task for a quest, it breaks questing while it is filling up. 

Going to any Reward or Task page beyond the first in a quest will snap back to the first page.

Stopping the RF Submission Station will make quests act normally again.

This is a very similar issue to my other one, at least in terms of what happens with quests : https://github.com/Funwayguy/BetterQuesting/issues/63

**Comment by Funwayguy** [comment]
This specific bug seems to originate from the base mod and not the expansion. I have a bug fix coming shortly that should resolve this bug. The other one is a bit more in depth so that may take some time to fix.
