### ISSUE TITLE
Not working with newest Beta

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/RFExpansion#4]
RF Expansion for Minecraft 1.7.10 not work together with newest Beta of Better Questing Mod.
 
With Theme pack
https://gist.github.com/Dream-Master/ab14d4ed6b9cb822b55f27963ab66aa1

Without Theme pack
https://gist.github.com/Dream-Master/9acf1013743a2ace0051b0094266e91f
 
Modpack
 
https://github.com/GTNewHorizons/NewHorizons

https://minecraft.curseforge.com/projects/themedquestingpack-expansion/issues/1

**Comment by Funwayguy** [comment]
RF Expansion is currently only for 1.x.x builds of Better Questing, not the beta 2.x.x builds. I'll likely not update RF Expansion to work with those until they're stable enough for full release

**Comment by Dream-Master** [comment]
Ok waiting for an Better Questin release then.
