### ISSUE TITLE
[1.10.2] RF Expansion not working with 2.x builds

### ISSUE THREAD

**Issue by xSparky911x** [Funwayguy/RFExpansion#5]
As per the title the updated 1.x build of RF expansion not working with 2.x builds of BQ.

BQ Version 2.3.184
BQ RF Expansion Version 1.3.19
Forge 2185

Crash Log
http://pastebin.com/DQYcNTHj

**Comment by Funwayguy** [comment]
There was an update... it just didn't make it to Curse. Resending it now...

**Comment by xSparky911x** [comment]
Seen updates for BQ and BQ Standard Expansion come through. Nothing for RF Expansion yet. Has there been a new one released for RF yet?

**Comment by xSparky911x** [comment]
Works well now thank you
